require 'sinatra'
require 'net/ssh'
require_relative 'api/connect'
require_relative 'api/addNode'
require_relative 'api/createModule'
require_relative 'api/removeNode'
require_relative 'api/fetchFacts'